### ISSUE TITLE
BlurEvent will probably cause jumping cursor (again)

### ISSUE THREAD

**Issue by desertfox94** [Sergio70/AceEditorV14#15]
The BlurEvent listens to the the 'editor-content' Event:
https://github.com/Sergio70/AceEditorV14/blob/ff76efb1024f2c24dc379b935f3b2fac2c79bdbf/src/main/java/com/hilerio/ace/BlurChanged.java#L11
This causes a call from the frontend to the backend every time the content changed (Not on Blur).

Further more a Listener is added to this event which updates the content.
https://github.com/Sergio70/AceEditorV14/blob/ff76efb1024f2c24dc379b935f3b2fac2c79bdbf/src/main/java/com/hilerio/ace/AceEditor.java#L30
Updating the content of the backend content will also cause an update in the frontend. We creating kind of a loop! Exactly this mechanism was causing the original issue #7.
@F0rce have you tested your solution with setting the Network speed to 'slow 3G' or typed really fast?

**Comment by F0rce** [comment]
@desertfox94 I completely changed the backend with my "blur" Logic.

the DomEvent("editor-content") is not doing the same anymore. I just reused the name.

The commuication between client and server only happens after the editor is blured (loses typing focus or a button is pressed etc)

https://github.com/Sergio70/AceEditorV14/blob/master/src/main/resources/META-INF/resources/frontend/%40granite-elements/ace-widget/ace-widget.js#L348-L356

I hope that clears some things up

**Comment by F0rce** [comment]
To see the communication between server and client - open the Browser Conolse and type in the editor. You will see no event triggered. But if you "click" outside of the Editor / trigger the blur event, something will appear in the console (communication between server and client).

**Comment by desertfox94** [comment]
Thanks for your quick reply!
I didn't noticed the changes in the frontend. You are completely right, very nice solution!
