### ISSUE TITLE
[Update] v1.0.0

### ISSUE THREAD

**Issue by F0rce** [Sergio70/AceEditorV14#24]
Hello everyone,

the last 3 weeks, I worked really hard on this widget and I'm really proud to say that version v1.0.0 is finally stable and ready to release.

I would like to thank @Sergio70 for trusting me and letting me contribute as much as I did and I really hope to continue my contribution in the future.

I'm going to write a full documentation by the end of the week.

Yours sincerely,
David

**Comment by Sergio70** [comment]
Excellent work, today I will post this version in the vaadin directory :)

**Comment by F0rce** [comment]
Hei @Sergio70 - with the release, could you please wait until maybe today evening or tomorrow. I'm working on some small features. 

Thank you,
David

**Comment by Sergio70** [comment]
@F0rce  Ok no problem, let me know when you have it ready and upload it of course counting our time difference.

**Comment by F0rce** [comment]
Seems like I have discovered a bug with vaadin, when this is resolved, u could publish the widget. Will keep you updated :)

**Comment by Sergio70** [comment]
Ok I understand, I will be pending 👍

**Comment by F0rce** [comment]
Hello @Sergio70 ,

I have wonderful news. Vaadin and myself were finally able to fix the issue.
As soon as I have finished my tests and pushed all my changes, this widget is finally ready for the "big release".

Again, thanks for letting me contribute <3
David

**Comment by F0rce** [comment]
Everything has been commited and merged. Have fun validating your tests. 

I adjusted the View a little bit to even test min, max width/height.

If you find (because I didn't) any sort of bug, just comment it here, and I will try to repair it as soon as possible.

Have a nice weekend. 

**v1.0.0 IS FINALLY STABLE AND READY TO RELEASE** <3
