### ISSUE TITLE
FOUND A BUG

### ISSUE THREAD

**Issue by F0rce** [Sergio70/AceEditorV14#27]
will keep you updated

**Comment by F0rce** [comment]
Has been fixed. I don't know to much about the vaadin directory but I pushed this hotfix as version 1.0.1 - if you can overwrite the 1.0.0 with it, it would be perfect.

But if not, I'm sorry. Due to my testfile I hadn't seen it.

Have a nice day :)

**Comment by Sergio70** [comment]
Hello, I did some tests and I found a problem when I close the Dialog component and the AceEditor shows the error "Uncaught TypeError: Cannot read the 'blur' property of null", apparently this is due to modifying with the blurevent.
With version 1.0 this error was not displayed.

On the vaadin directory you cannot overwrite a version and the next update in the directory will be 1.0.1.

Have a nice day, I'll be on top of this.

**Comment by F0rce** [comment]
I'll check it out :) thanks for your input

**Comment by F0rce** [comment]
I'm currently in support chat of vaadin. It seems like the error you and I are getting is not to the widget related. It is probably related to the live-reload widget of vaadin.

https://github.com/vaadin/flow/issues/8984

**Comment by F0rce** [comment]
Ok @Sergio70 ,

you can push the widget to the directory. The error we are getting is not to the widget related, it is realted to jetty. (If you would run the widget with Spring the error **should** not appear.
Right now I pushed some general cleanup.

![Screenshot 2020-12-02 101401](https://user-images.githubusercontent.com/60381251/100852892-64b8e400-3487-11eb-8529-d9fec33f9711.png)

**Comment by Sergio70** [comment]
Ok I understand, Thanks @F0rce  for all this makes sense :).
The widget was published in the directory.

**Comment by F0rce** [comment]
Thanks Sergio 🥰

Have a nice week :)

**Comment by lipisak** [comment]
Hi @F0rce and @Sergio70,
I am getting the blur error you mentioned above. It occurs when the editor is detached from UI. whenever I close the detail with ACE editor this error appears: TypeError: null is not an object (evaluating '$0.blur')
I am not using the chat at all. So it is not the cause of this issue.

Thx
J

**Comment by F0rce** [comment]
Hei @lipisak

Are you on version 1.0.0 or 1.0.1 ?

Thanks,
David

**Comment by Sergio70** [comment]
Hi @lipisak  this only happens in development, when you package your application in productive mode this does not generate the error.
Hi @F0rce, I think it is better to leave the widge before the https://github.com/Sergio70/AceEditorV14/commit/3bcc385c9078a0c0d6c7bbfc550c4141e4350eee change that does not show this error, as I mentioned earlier this error is not observed in productive mode.

**Comment by lipisak** [comment]
Hi guys,
I am on 1.0.1 version. I am not sure if it is only on dev version. But it’s possible. 

Lipisak

**Comment by F0rce** [comment]
The refresh is mandatory - else the editor will lose settings when changing visibility etc. I could look into it a bit further tomorrow.
