### ISSUE TITLE
Found issues or want more features ?

### ISSUE THREAD

**Issue by F0rce** [Sergio70/AceEditorV14#32]
Post them here.

I will take a look at it as fast as possible, because I returned from my school and holiday break.

~ David

**Comment by Sergio70** [comment]
Hi @F0rce , no other bugs have been reported and the component is very complete thanks to your help. I send you my regards and success in your studies, take good care of yourself in these difficult times.

**Comment by F0rce** [comment]
I really appreciate you :) if someone has any requests ill be happy to implement Them :)

**Comment by Sergio70** [comment]
Thanks, of course if something comes up I'll let you know, greetings :)
