### ISSUE TITLE
Quality of Life #1

### ISSUE THREAD

**Issue by F0rce** [Sergio70/AceEditorV14#33]
Hello @Sergio70 ,

this issue is just here to inform you, that in today (or in the next few days) I will be uploading a new version of the ace-editor. The last few days I was playing quite a bit with the ace-editor and found some small "issues" regarding visibility and flow. There was also a small mistake in the synchronisation of the current selection which was also fixed. 

I think some people will appreciate these changes :)

Stay safe,
David

**Comment by F0rce** [comment]
Everything has been uploaded and tested carefully.

But please validate and test it yourself.

Thanks in advance,
David

**Comment by F0rce** [comment]
*please wait for my answer* 

working on smth else

**Comment by F0rce** [comment]
everything is stable and ready to roll out. Thanks for your patience

**Comment by Sergio70** [comment]
Hello, good morning @F0rce, thanks for your contributions, today I will upload the new version to the vaadin directory.  👍 :)
