### ISSUE TITLE
[FeatureRequest] more setters like printMargin, showInvisibles etc.

### ISSUE THREAD

**Issue by sirbris** [Sergio70/AceEditorV14#5]
Hi there,

first of all: thank you for this component, really appreciate the time!

Following setters would be nice:
setShowPrintMargin(boolean value);
setShowInvisibles(boolean value);
setShowGutter(boolean value);
setHighlightActiveLine(boolean value);

**Comment by Sergio70** [comment]
Hello, unfortunately, I have not had much time to support the component, if you can make these modifications and I agree as a collaborator to update the component

**Comment by F0rce** [comment]
@sirbris Hi, I saw that @Sergio70 merged all of my new implementions. These also include the setters you mentioned earlier.

@Sergio70 could you please upload the new changes into the Vaadin Directory so the people could use it? Thanks in advance and thanks for merging all my pull request.

Have a great Weekend,
David

**Comment by Sergio70** [comment]
Yes, today I will upload this to the vaadin repository, an apology for being little active to the component.

**Comment by Sergio70** [comment]
The component has been uploaded to the vaadin repository, thank you very much for all your effort and contribution in the @F0rce  component.

**Comment by desertfox94** [comment]
Thanks a lot @F0rce and @Sergio70! Great work 🥇
