### ISSUE TITLE
The next step 🥇 

### ISSUE THREAD

**Issue by F0rce** [Sergio70/AceEditorV14#61]
Dear @Sergio70,

it was a great pleasure working with you. I really want to thank you, for trusting me and letting me contribute as much as I wanted / needed to.

With Polymer 3 / Polymer-Element going end of life pretty soon and Vaadin's full support of Lit-Element (the newest and faster Webcomponent framework) I created a whole new version of the ace editor. With more functions, better lifecyle and so on.

I already told the people, that had problems with the current version ( #58 #56 ), to switch to the newer version to fix their issues, which was a great success.

So from now on, I will be focussing / maintaing the newer / current version of the ace editor:
https://github.com/f0rce/ace                               <-- Vaadin Add-on source code
https://github.com/f0rce/lit-ace                           <-- Frontend source code
https://vaadin.com/directory/component/ace      <-- Vaadin Directory
https://www.npmjs.com/package/@f0rce/lit-ace  <-- Frontend NPM package
https://docs.f0rce.de/ace                                     <-- Documentation

I hope you are doing well in those difficult times and I hope that we will keep in touch.

Have a great day,
David Dodlek

**Comment by Sergio70** [comment]
Hello @F0rce David I hope you're well, thank you for your support during this time and I agree with you and I wish you much success in your future projects, I send you a big hug, greetings from Mexico.
