### ISSUE TITLE
Cursor jumps to the end of text

### ISSUE THREAD

**Issue by lipisak** [Sergio70/AceEditorV14#7]
When I type quickly to the editor the cursor jumps at the end of text. It doesn't happen when I write slowly.
It hapens in version 1.4 Beta

**Comment by gdressino** [comment]
I think this happens because the editorChangeAction sends the changes to the server, the server responds and valueChanged is executed. The problem is worse with high latency (you can simulate it with Chrome, on Network Throttling).

I have this uggly and inelegant workaround:

First, we only send the last value when you are typing fast, to avoid sending all the text on every keystroke.

```
  editorChangeAction() {
    if(this.editorChanges == undefined)
      this.editorChanges = 0;
    this.editorChanges++;
    //console.debug("[ace-widget] editorChangeAction++ "+this.editorChanges);
    setTimeout(() => {
            this.editorChanges--;
            //console.debug("[ace-widget] editorChangeAction-- "+this.editorChanges);
    	    if(this.editorChanges==0){
    	         //console.debug("[ace-widget] editorChangeAction", {value: this.editorValue, oldValue: this._value});
   	          this.dispatchEvent(new CustomEvent('editor-content', {detail: {value: this.editorValue, oldValue: this._value}}));
    	    }
    	}, 500);
  }
```

Then, only accept value changes when we aren't typing, and preserve cursor position:

```
  valueChanged() {
    //console.debug("[ace-widget] valueChanged - ",this.value)
    if (this.editor == undefined) {
      return;
    }
    if (this.editorValue != this.value 
    		&& (this.editorChanges==0 || this.editorChanges==undefined)) {
      var cp=this.editor.getCursorPosition();
      this.editorValue = this.value;
      this.editor.clearSelection();
      this.editor.resize();
      if(cp != undefined && cp!=null)
        this.editor.moveCursorToPosition(cp);
    }
  }
```

**Comment by desertfox94** [comment]
I think its a backend problem.
Have look at the current mechanism to update the editors value in the backend:

```java
        @Override
	protected void onAttach(AttachEvent attachEvent) {
		super.onAttach(attachEvent);
		addListener(ChangeEvent.class, this::updateValue); // Process the change event of the frontend.
	}

	public void updateValue(ChangeEvent event) {
		setValue(event.getValue());
	}

	/**
	 * Sets value for the editor.
	 */
	public void setValue(String value) {
		getElement().setProperty("value", value);
	}
```

The Problems is the call of `getElement().setProperty("value", value);`. It updates the backend as well as the frontend.

So the backend triggers the update the frontend with the content send by the frontend. The frontend in most cases will be prevent the update, unless you type very fast (@lipisak) or have a high latency (@gdressino).

**Comment by F0rce** [comment]
I think, I found the solution.

I cant really explain why it works now, but in my tests, it never skipped to the ending. This was literally just some basic thinking to force it, to finish processing one single value. I don't lose/skip any values or anything. Could maybe someone more intelligent then me, explain why it works now the way I did it ?

```
	private Boolean processing = false;

	@Override
	protected void onAttach(AttachEvent attachEvent) {
		super.onAttach(attachEvent);
		addListener(ChangeEvent.class, this::updateValue);
	}

	public void updateValue(ChangeEvent event) {
		processing = true;
		setValue(event.getValue());
		processing = false;
	}

	public void setValue(String value) {
		if (!processing) {
			getElement().setProperty("value", value);
		} // else - save value in a List and iterate over the list in the correct order and set the value to the editor (not needed bc it works :^))
	}

```

Could maybe someone else try it and tell me their results ( @desertfox94 ) ?

Thanks in advance,
David

**Comment by desertfox94** [comment]
Turned out not only the frontend also the backend had some problems.
Hope this will help you. You may contact me if you have any problems or questions :)

**Comment by F0rce** [comment]
I think this Issue could be closed by now.

Thanks for the merge 👍🏼

**Comment by lipisak** [comment]
Hi,
I haven't tried this yet as the new version has not been released. But I can close this issue

J.
